#1 난수(Random Number)발생 알고리즘

In [ ]:
import numpy as np  #numpy라는 난수발생 알고리즘 라이브러리를 실행합니다. 그리고 np라고 축약합니다.

In [ ]:
np.random.rand(5) #0에서 1까지 있는 수 중에 5개를 랜덤으로 뽑습니다. 

array([0.53499178, 0.86154429, 0.24287511, 0.89357244, 0.0657084 ])

In [ ]:
np.random.rand(5) #0에서 1까지 있는 수 중에 5개를 랜덤으로 뽑습니다. 명령어를 실행할때 마다 달라집니다. 

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10) #0에서 1까지 있는 수 중에 10개를 랜덤으로 뽑습니다. 

array([0.15362162, 0.30779718, 0.10051848, 0.79711608, 0.20042531,
       0.01654847, 0.1144813 , 0.16638491, 0.57280524, 0.87465186])

In [ ]:
np.random.seed(0) #난수 생성 중에 특정한 패턴을 지정합니다
np.random.rand(5) #0에서 1까지 있는 수 중에 5개를 랜덤으로 뽑습니다. 


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.seed(0) #난수 생성 중에 특정한 패턴을 지정합니다
np.random.rand(5) #0에서 1까지 있는 수 중에 5개를 랜덤으로 뽑습니다. 

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
x=np.arange(10) #랜덤으로 0부터 9까지 나옵니다. 
np.random.permutation(x) #순서를 랜덤하게 바꿉니다. 

array([3, 1, 8, 7, 9, 0, 6, 4, 2, 5])

In [ ]:
x=np.arange(10)
np.random.permutation(x) #순서를 랜덤하게 바꿉니다. 

array([5, 2, 3, 4, 1, 0, 9, 8, 7, 6])

#2 샘플 뽑기 
np.random.choice(a, size=None, replace=True, p=None)

a: 배열, 
size: 샘플 숫자 
repalce : 복원/비복원 
p: 배열, 데이터가 선택될 확률 

In [ ]:
np.random.choice(5,5,replace=False) #0부터 4까지 배열, 0이 들어간다. 

array([2, 3, 4, 1, 0])

In [ ]:
np.random.choice(5,5,replace=False)

array([2, 4, 1, 3, 0])

In [ ]:
x=np.arange(10) #0부터 9까지  나옵니다. 
np.random.choice(x,5) #0부터 9까지 나오는 배열 중에 5개를 뽑는다. 

array([0, 2, 3, 8, 1])

In [ ]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) #0부터 4까지 중에 10번을 뽑는다 그런데 1과 4는 확률이 0

array([3, 3, 2, 3, 2, 3, 3, 3, 2, 3])

#3 로또 번호 만들어 드립니다. 

In [ ]:
import random as rp #무작위+중복방지 

In [ ]:
lotto=rp.sample(range(1,46),6) #1부터 46개 중에 6개를 뽑습니다. 
print(lotto)

[23, 7, 22, 9, 4, 19]
