#1 난수(Random Number)발생 알고리즘

In [1]:
import numpy as np  #numpy라는 난수발생 알고리즘 라이브러리를 실행합니다. 그리고 np라고 축약합니다.

In [2]:
np.random.rand(5) #0에서 1까지 있는 수 중에 5개를 랜덤으로 뽑습니다. 

array([0.36033394, 0.09202929, 0.44949513, 0.9901725 , 0.34912067])

In [3]:
x=np.arange(10) #랜덤으로 0부터 9까지 나옵니다. 
np.random.permutation(x) #순서를 랜덤하게 바꿉니다. 

array([3, 8, 9, 1, 5, 0, 7, 4, 2, 6])

In [4]:
m=np.mean(x)
print(m)

4.5


#2 표본 추출 및 통계량 계산
np.random.choice(a, size=None, replace=True, p=None)

a: 배열, 
size: 샘플 숫자 
repalce : 복원/비복원 
p: 배열, 데이터가 선택될 확률 

In [5]:
x1=np.random.choice(x,5,replace=False) #5개 뽑기 
print(x1)

[1 4 9 8 7]


In [6]:
m1=np.mean(x1)
print(m1)

5.8


In [7]:
x2=np.random.choice(x,5,replace=False) #5개 뽑기 
print(x2)

[2 3 7 0 5]


In [8]:
m2=np.mean(x2)
print(m2)

3.4


In [9]:
x3=np.random.choice(x,5,replace=False) #5개 뽑기 
print(x3)

[5 7 4 2 0]


In [10]:
m3=np.mean(x3)
print(m3)

3.6
